language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

env:
  - DOJO_DIR=05-05-2016
  - DOJO_DIR=27-01-2017

before_script:
  - composer selfupdate

script:
  - cd $DOJO_DIR && composer install && phpunit